# -*- coding: utf-8 -*-
"""
@author: Nayden Dochev
"""

texts = [

# Vladimir Vazov
"""
Vladimir Vazov was born on May 14, 1868 to Mincho Vazov and Suba Hadjinikolova. His brothers were the writer Ivan Vazov, the officer Georgi Vazov and the politician Boris Vazov.
In 1886 Vladimir Vazov entered the Military School in Sofia. After he graduated in 1888 he was assigned as a second lieutenant to the 5th artillery regiment in Shumen.
On the 18th of May 1890 Vladimir was promoted to lieutenant and continued his specialization in Hessen, Germany. On 2 of August 1894 he received the rank of captain and in 1896 was transferred to the 4th Artillery Regiment in Sofia and served as the commander of an artillery battery. During 1902 and 1903 he attended Artillery School in Tsarskoye Selo, Russia. In 1904 Vladimir was part of a special Bulgarian delegation which visited France and Germany to asses the capabilities of their newest artillery equipment and choose a supplier for the Bulgarian Army. On 17 of February 1906 the minister of war decreed the establishment of a special Artillery School in Sofia and Vladimir Vazov was assigned as its assistant principal. On 31 of December of the same year he was promoted to the rank of lieutenant colonel. In 1909 he was the commander of an artillery section in the 4th Artillery Regiment but was soon made a brigade commander.

During the First Balkan War Vladimir Vazov served as commander of the 4th Quick-Firing Artillery Regiment of the 1st Sofia Infantry Division. When the war was declared on 5 of October 1912 some 21 officers and 1168 soldiers were serving in his regiment.
On the 9th of October Vazov fought around the village of Geçkinli where the Bulgarians defeated the Ottomans despite the latter's sizable numerical advantage. After that he took part in the Battle of Kirk Kilisse and later fought in the First Battle of Çatalca.
During the Second Balkan War Vladimir retained the command of his regiment and participated in the fighting around Tsaribrod, Pirot, Bubliak ad Gradoman.

By August 1915 lieutenant colonel Vazov was serving as commander of the 5th Division's artillery brigade[1]. In October of the same year the division was subordinated to the Bulgarian 2nd Army which was conducting operations against the Serbians in Vardar Macedonia. Here the lieutenant-colonel and his brigade took part in the heavy fighting around the town of Gnjilane, during the Battle of Kosovo. With the final defeat of the Serbian army in November the 5th Division was turned south to face the French forces advancing up the river Vardar. On 28 of November Vazov was severely wounded and forced to take leave from active frontal duties during the next several months[1]. Soon afterwards he was promoted to colonel
In 1916 he was made commander of the 1st Infantry Brigade of the 5th Division and successfully led it in action against Allies during their Autumn Offensive on the Macedonian Front[1].
On 1 of March 1917 he took the command of the 9th Pleven Infantry Division which was part of the First Bulgarian Army. Beginning in 1916 the division occupied a stretch of the Macedonian Front between the river Vardar and lake Dojran.
As soon as he was appointed he inspected the entire section of the front that was under his command and took measures to strengthen and fortify it. Under his guidance the forced were deployed in order to create a defence in depth.
His efforts to improve the positions were soon tested during the Second Battle of Doiran between 22 and 26 of April 1917. Some 86 heavy and 74 field British guns bombarded the line with more than 100,000 shells but caused insignificant damage and the following infantry attack suffered a heavy defeat. In early May the British resumed their assault but were again defeated and suffered heavy casualties. Following this attack the Bulgarian 34th Troyan Regiment alone buried the bodies of some 2,290 Allied officers and soldiers. Due to his significant contribution for the victory on 20 of May 1917 Vladimir Vazov was promoted to major general.

The location of the Doiran Sector was crucial as it represented the shortest possible route to the valley of the Vardar and during the summer of 1918 its the defence was expanded to consisted of for lines arrayed in depth. Hence it was much better prepared to face an attack than the previous year.
When the Allied Vardar Offensive began the British and two Greek divisions once again attacked the 9th Pleven Division at Doiran. During this Third Battle of Doiran the Allies once again enjoyed significant advantage in firepower and manpower, being able to bombard the Bulgarian position with over 300,000 ordinary and gas shells. Despite this the damage to the fortifications was limited and the fighting again resulted in a decisive Bulgarian victory. According to official British sources the Allied losses totalled just over 7,000. Bulgarian sources however report a figure of over 11,000. The Bulgarian and German commanders on the Macedonian Front were not able to fully use the results of the decisive victory at Doiran to their advantage and Bulgaria signed an armistice on 29 of September 1918 thus ending its participation in the First World War.
On February 24, 1920 lieutenant-general Vazov went into the reserve. In 1926 he became mayor of Sofia. During his mandate (until 1932) the fire department was reformed, the electrical network expanded, and the public transport improved. Sofia became one of the “greenest” capitals in Europe.
Among the most notable moments of Vladimir Vazov’s life was his visit to England in 1936. The British legion celebrated the British victory in World War I. The British veterans invited one of their worthiest opponents on the battlefield. He was personally greeted by Lord Milne, who shook his hand with the words "It is a pleasure to meet the Bulgarian delegation, as even though we were enemies, you - like us - fought not only like brave men, but also like gentlemen." The British paid great honour to General Vazov as they lowered their national flags in his name. The chairman of the British legion Major Goldy said in his speech: “He is one of the few foreign officers whose name features in our history”.
The last years of his life were spent in the village of Ribaritsa (near Lovech), where he died in 1945.
""",

# Pyotr Ilyich Tchaikovsky 
"""
Pyotr Ilyich Tchaikovsky was a Russian composer whose works included symphonies, concertos, operas, ballets, chamber music, and a choral setting of The Russian Orthodox Divine Liturgy. Some of these are among the most popular concert and theatrical music in the classical repertoire. He was the first Russian composer whose music made a lasting impression internationally, which he bolstered with appearances as a guest conductor later in his career in Europe and the United States. One of these appearances was at the inaugural concert of Carnegie Hall in New York City in 1891. Tchaikovsky was honored in 1884 by Emperor Alexander III, and awarded a lifetime pension in the late 1880s.

Although musically precocious, Tchaikovsky was educated for a career as a civil servant. There was scant opportunity for a musical career in Russia at that time, and no system of public music education. When an opportunity for such an education arose, he entered the nascent Saint Petersburg Conservatory, from where he graduated in 1865. The formal Western-oriented teaching he received there set him apart from composers of the contemporary nationalist movement embodied by the Russian composers of The Five, with whom his professional relationship was mixed. Tchaikovsky's training set him on a path to reconcile what he had learned with the native musical practices to which he had been exposed from childhood. From this reconciliation, he forged a personal, independent but unmistakably Russian style—a task that did not prove easy. The principles that governed melody, harmony and other fundamentals of Russian music ran completely counter to those that governed Western European music; this seemed to defeat the potential for using Russian music in large-scale Western composition or from forming a composite style. Russian culture exhibited a split personality, with its native and adopted elements having drifted apart increasingly since the time of Peter the Great, and this resulted in uncertainty among the intelligentsia of the country's national identity. The principles of Russian nationalist artists were fundamentally at odds with those supporting European traditions, and this caused personal antipathies that dented Tchaikovsky's self-confidence.

Despite his many popular successes, Tchaikovsky's life was punctuated by personal crises and depression. Contributory factors included his leaving his mother for boarding school, his mother's early death and the collapse of the one enduring relationship of his adult life, his 13-year association with the wealthy widow Nadezhda von Meck. His same-sex orientation, which he kept private, has traditionally also been considered a major factor, but musicologists now play down its importance. His sudden death at the age of 53 is generally ascribed to cholera; there is an ongoing debate as to whether it was accidental or self-inflicted.

While his music has remained popular among audiences, critical opinions were initially mixed. Some Russians did not feel it sufficiently representative of native musical values and were suspicious that Europeans accepted it for its Western elements. In apparent reinforcement of the latter claim, some Europeans lauded Tchaikovsky for offering music more substantive than base exoticism, and thus transcending stereotypes of Russian classical music. Tchaikovsky's music was dismissed as "lacking in elevated thought," according to longtime New York Times music critic Harold C. Schonberg, and its formal workings were derided as deficient for not following Western principles stringently. Vestiges of this last claim still remain in some critical circles, but by the end of the 20th century, Tchaikovsky's status as a significant composer had become secure, with increasing numbers responding positively to its tunefulness and innovation.

The Tchaikovsky family in 1848. Left to right: Pyotr, Alexandra Andreyevna (mother), Alexandra (sister), Zinaida, Nikolai, Ippolit, Ilya Petrovich (father)

Pyotr Ilyich Tchaikovsky was born in Votkinsk, a small town in present-day Udmurtia, a former province of Vyatka in the Russian Empire. His family had a long line of military service. His father, Ilya Petrovich Tchaikovsky, was an engineer who served as a lieutenant colonel in the Department of Mines. He was mostly of Russian ethnicity, though his ancestors were Ukrainian Cossacks[1] and manager of the Kamsko-Votkinsk Ironworks. His grandfather, Petro Fedorovych Chaika, received medical training in Saint Petersburg and served as a physician's assistant in the army before becoming city governor of Glazov in Viatka. His great-grandfather, a Cossack named Fyodor Chaika, distinguished himself under Peter the Great at the Battle of Poltava in 1709.[2] His mother, Alexandra Andreyevna née d'Assier, the second of Ilya's three wives, was 18 years her husband's junior and of French ancestry on her father's side.[3] Both of Tchaikovsky's parents were trained in the arts, including music. This was considered a necessity as a posting to a remote area of Russia was always possible, bringing with it a need for entertainment, both private and at social gatherings.[4]

Tchaikovsky had four brothers (Nikolai, Ippolit, and twins Anatoly and Modest), a sister, Alexandra and a half-sister Zinaida from his father's first marriage.[5] He was particularly close to Alexandra and the twins. Anatoly later had a prominent legal career, while Modest became a dramatist, librettist, and translator.[6] Alexandra married Lev Davydov[7] and had seven children, one of whom, Vladimir Davydov, became very close to the composer, who nicknamed him 'Bob'.[8] The Davydovs provided the only real family life Tchaikovsky knew as an adult,[9] and their estate in Kamenka (now Kamianka, Cherkasy Oblast, part of Ukraine) became a welcome refuge for him during his years of wandering.[9]

In 1843 the family hired Fanny Dürbach, a 22-year-old French governess, to look after the children and teach Tchaikovsky's elder brother Nikolai and a niece of the family.[10] While Tchaikovsky, at four and a half, was initially considered too young to begin studies, his insistence convinced Dürbach otherwise.[11] Dürbach proved an excellent teacher, teaching Pyotr Tchaikovsky to be fluent in French and German by the age of six.[4] Tchaikovsky became attached to the young woman and her affection for him is said to have provided a counter to Tchaikovsky's mother, who has been described as a cold, unhappy, distant parent,[12] although others assert that the mother doted on her son.[13] Dürbach saved much of Tchaikovsky's work from this period, which includes his earliest known compositions. She was also the source of several anecdotes about his childhood.[14]

Tchaikovsky took piano lessons from the age of five. A precocious pupil, he could read music as adeptly as his teacher within three years. His parents were initially supportive, hiring a tutor, buying an orchestrion (a form of barrel organ that could imitate elaborate orchestral effects), and encouraging his study of the piano for both aesthetic and practical reasons. Nevertheless, the family decided in 1850 to send Tchaikovsky to the Imperial School of Jurisprudence in Saint Petersburg. This decision may have been rooted in practicality. It is not certain whether Tchaikovsky's parents had grown insensitive toward his musical gift.[4] However, regardless of talent, the only avenues for a musical career in Russia at that time – except for the affluent aristocracy – were as a teacher in an academy or an instrumentalist in one of the Imperial Theaters. Both were considered on the lowest rung of the social ladder, with no more rights than peasants.[15] Also, because of the growing uncertainty of his father's income, both parents may have wanted Tchaikovsky to become independent as soon as possible.[16]

Since both parents had graduated from institutes in Saint Petersburg, they decided to educate him as they had themselves been educated.[17] The School of Jurisprudence mainly served the lesser nobility and would prepare Tchaikovsky for a career as a civil servant. As the minimum age for acceptance was 12 and Tchaikovsky was only 10 at the time, he was required to spend two years boarding at the Imperial School of Jurisprudence's preparatory school, 800 miles (1,300 km) from his family.[18] Once those two years had passed, Tchaikovsky transferred to the Imperial School of Jurisprudence to begin a seven-year course of studies.[19]
Emerging composer
Childhood trauma and school years
A row of large, stone three-story buildings alongside a large riverbank.
Modern view of the Imperial School of Jurisprudence

Tchaikovsky's separation from his mother to attend boarding school caused an emotional trauma that tormented him throughout his life.[20] Her death from cholera in 1854 further devastated him, affecting him so much that he could not inform Fanny Dürbach until two years later.[21] He mourned his mother's loss for the rest of his life[22] and called it "the crucial event" that ultimately shaped it.[23] More than 25 years after his loss, Tchaikovsky wrote to his patroness, Nadezhda von Meck, "Every moment of that appalling day is as vivid to me as though it were yesterday."[22] The loss also prompted Tchaikovsky to make his first serious attempt at composition, a waltz in her memory.

Tchaikovsky's father, who also contracted cholera at this time but fully recovered, immediately sent him back to school, hoping that classwork would occupy the boy's mind.[24] In partial compensation for his isolation and loss, Tchaikovsky made lifelong friendships with fellow students, including Aleksey Apukhtin and Vladimir Gerard.[25] Music became a unifier. While it was not an official priority at the School of Jurisprudence, Tchaikovsky maintained an extracurricular connection by regularly attending the opera with other students.[26] Fond of works by Rossini, Bellini, Verdi and Mozart, he would improvise for his friends at the school's harmonium on themes they had sung during choir practice. "We were amused," Vladimir Gerard later remembered, "but not imbued with any expectations of his future glory."[27] Tchaikovsky also continued his piano studies through Franz Becker, an instrument manufacturer who made occasional visits to the school; however, the results, according to musicologist David Brown, were "negligible."[28]

In 1855, Tchaikovsky's father funded private lessons for his son with the teacher Rudolph Kündinger. He also questioned Kündinger about a musical career for the boy. Kündinger replied that, while impressed, nothing suggested to him a future as a composer or performer.[29] Kündinger later admitted that his assessment was also based on his own negative experiences as a musician in Russia and his unwillingness for Tchaikovsky to be treated likewise.[30] Tchaikovsky was told to finish his course and then try for a post in the Ministry of Justice.[31] Even though he gave this practical advice, his father remained receptive about a career in music for Tchaikovsky. He simply did not know what Tchaikovsky could accomplish, nor whether he could make a living at it. No public education system in music existed at the time in Russia and private education, especially in composition, was erratic.[32]
Civil service; pursuing music
A clean-shaven man in his teens wearing a dress shirt, tie and dark jacket.
Tchaikovsky in his teens

On 10 June 1859, the 19-year-old Tchaikovsky graduated with the rank of titular counselor, a low rung on the civil service ladder. Appointed five days later to the Ministry of Justice, he became a junior assistant within six months and a senior assistant two months after that. He remained a senior assistant for the rest of his three-year civil service career.[33]

In 1861, Tchaikovsky attended classes in music theory taught by Nikolai Zaremba at the Mikhailovsky Palace (now the Russian Museum) in Saint Petersburg.[34] These classes were organized by the Russian Musical Society (RMS), founded in 1859 by the Grand Duchess Elena Pavlovna (a German-born aunt of Tsar Alexander II) and her protégé, pianist and composer Anton Rubinstein. The aim of the RMS was to foster native talent, in accordance with Alexander II's stated intent.[35] Previous tsars and the aristocracy had focused almost exclusively on importing European talent.[36] The RMS fulfilled Alexander II's wish by promoting a regular season of public concerts (previously held only during the six weeks of Lent when the Imperial Theaters were closed[37]) and providing basic professional training in music.[38] The classes held at the Mikhailovsky Palace were a precursor to the Saint Petersburg Conservatory, which opened in 1862. Tchaikovsky enrolled at the Conservatory as part of its premiere class but held onto his Ministry post until the following year, wanting to make sure his course lay in music.[39] From 1862 to 1865 he studied harmony and counterpoint with Zaremba. Rubinstein, director and founder of the Conservatory, taught instrumentation and composition.[40]

Tchaikovsky benefited from his Conservatory studies in two ways. First, it transformed him into a musical professional and gave him tools that helped him thrive as a composer. Second, his in-depth exposure to European principles and forms for organizing musical material gave Tchaikovsky the sense that his art belonged to world culture and was not exclusively Russian or Western.[41] This mindset became important in his reconciling Russian and European influences in his compositional style and showed that both these aspects of Russian culture were actually "intertwined and mutually dependent."[42] It also became a starting point for other Russian composers to build their own individual styles.[43]
Anton (right) and Nikolai Rubinstein

While Rubinstein was impressed by Tchaikovsky's musical talent on the whole[44] (citing him as "a composer of genius" in his autobiography[45]), he was less pleased with the more progressive tendencies of some of Tchaikovsky's student work.[46] Nor did he change his opinion as Tchaikovsky's reputation grew in the years following his graduation.[a 3][a 4] He and Zaremba clashed with Tchaikovsky when he submitted his First Symphony for performance by the RMS in Saint Petersburg. Rubinstein and Zaremba refused to consider the work unless substantial changes were made. Tchaikovsky complied but they still refused to perform the symphony.[47] Tchaikovsky, distressed that he had been treated as though he were still their student, withdrew the symphony. It was given its first complete performance, minus the changes Rubinstein and Zaremba had requested, in Moscow in February 1868.[48]

After graduating from the Conservatory, Tchaikovsky briefly considered a return to public service due to pressing financial needs. However, Rubinstein's brother Nikolai offered the post of Professor of Music Theory at the soon-to-open Moscow Conservatory. While the salary for his professorship was only 50 rubles a month, the offer itself boosted Tchaikovsky's morale and he accepted the post eagerly. He was further heartened by news of the first public performance of one of his works, his Characteristic Dances, conducted by Johann Strauss II at a concert in Pavlovsk Park on 11 September 1865 (Tchaikovsky later included this work, retitled, Dances of the Hay Maidens, in his opera The Voyevoda).[49]

From 1867 to 1878, Tchaikovsky combined his professorial duties with music criticism while continuing to compose.[50] This exposed him to a range of contemporary music and afforded him the opportunity to travel abroad.[51] In his reviews, he praised Beethoven, considered Brahms overrated and took Schumann to task for poor orchestration.[52][a 5] He appreciated the staging of Wagner's Der Ring des Nibelungen at its inaugural performance in Bayreuth, Germany, but not the music, calling Das Rheingold "unlikely nonsense, through which, from time to time, sparkle unusually beautiful and astonishing details."[53] A recurring theme he addressed was the poor state of Russian opera.[54]
Relationship with The Five
See also: Pyotr Ilyich Tchaikovsky and The Five
A man in his late 20s or early 30s with dark hair and a bushy beard, wearing a dark coat, dress shirt and tie.
The young Mily Balakirev

In 1856, while Tchaikovsky was still at the School of Jurisprudence and Anton Rubinstein lobbied aristocrats to form the RMS, critic Vladimir Stasov and an 18-year-old pianist, Mily Balakirev, met and agreed upon a nationalist agenda for Russian music. Taking the operas of Mikhail Glinka as a model, they espoused a music that would incorporate elements from folk music, reject traditional Western methods of musical expression and use exotic harmonic devices such as the whole tone and octatonic scales.[55] Moreover, they saw Western-style conservatories as unnecessary and antipathetic to fostering native talent; imposing foreign academics and regimentation would stifle the Russian qualities Balakirev and Stassov wished to nurture.[56] Followers trickled in. César Cui, an army officer who specialized in the science of fortifications, and Modest Mussorgsky, a Preobrazhensky Lifeguard officer, came in 1857. Nikolai Rimsky-Korsakov, a naval cadet, followed in 1861 and Alexander Borodin, a chemist, in 1862. Like Balakirev, they were not professionally trained in composition but possessed varying degrees of musical proficiency. Together, the five composers became known as the moguchaya kuchka, translated into English as the Mighty Handful or The Five.[57]

Balakirev and Stassov's efforts fueled a debate, begun by Russian intelligentsia in the 1830s, over whether artists negated their Russianness when they borrowed from European culture or took vital steps toward renewing and developing their culture.[58] Rubinstein's criticism of amateur efforts in musical composition (he insisted that creativity without discipline was a waste of talent) and his pro-Western outlook and training fanned the flames further. His founding a professional institute where predominantly foreign professors taught alien musical practices heated the controversy to boiling point.[59] Balakirev attacked Rubinstein for his musical conservatism and his belief in professional music training.[60] Mussorgsky jumped on the bandwagon, calling the Conservatory a place where professors, dressed "in professional, antimusical togas, first pollute their students' minds, then seal them with various abominations."[61] Tchaikovsky and his fellow conservatory students were caught in the middle, well-aware of the argument but directed by Rubinstein to remain silent and focus on their own artistry.[62] Nevertheless, as Rubinstein's pupil, Tchaikovsky became a target for The Five's scrutiny and was criticized for not following their precepts.[63] Cui, who championed the nationalist cause as a music critic for the next half-century, wrote a blistering review of a cantata Tchaikovsky had composed as his graduation thesis. The review devastated the composer.[64]

In 1867, Rubinstein resigned as conductor of the RMS orchestra and was replaced by Balakirev. Tchaikovsky, now Professor of Music Theory at the Moscow Conservatory,[65] had already promised his Characteristic Dances to that ensemble but felt ambivalent. He wanted to fulfil his commitment, but had concerns over sending his composition to someone whose musical aims ran counter to his own and could thus be considered hostile.[66] Compounding the issue was Balakirev's mentoring of composers whose work Tchaikovsky did not admire.[67] He eventually sent the Dances but enclosed a request for encouragement should they not be performed.[66] Balakirev, whose influence over the other composers in The Five had meanwhile waned, may have sensed the potential for a new disciple in Tchaikovsky.[68] He replied "with complete frankness" that he considered Tchaikovsky "a fully fledged artist".[69] These letters set the tone for their relationship over the next two years. In 1869, they worked together on what became Tchaikovsky's first recognized masterpiece, the fantasy-overture Romeo and Juliet, a work which The Five wholeheartedly embraced.[70] The group also welcomed his Second Symphony, subtitled the Little Russian.[71] In its original form, Tchaikovsky allowed the unique characteristics of Russian folk song to dictate the symphonic form of its outer movements, rather than Western rules of composition. This was a primary aim of The Five.[72] (Tchaikovsky became dissatisfied with this approach, however, made a large cut in the finale and rewrote the opening movement along Western lines when he revised the symphony seven years later.)[73]

While ambivalent about much of The Five's music, Tchaikovsky remained on friendly terms with most of its members.[74] Despite his collaboration with Balakirev, Tchaikovsky made considerable efforts to ensure his musical independence from the group as well as from the conservative faction at the Saint Petersburg Conservatory.[75]
Growing fame; budding opera composer

Tchaikovsky's successes during his first years as a composer were infrequent, won with tremendous effort. The disappointments in between exacerbated a lifelong sensitivity to criticism. Also, while Nikolai Rubinstein expended considerable effort in spreading Tchaikovsky's music, he was also given to fits of rage in private with the composer in critiquing it.[76] One of these rages, later documented by Tchaikovsky, involved Rubinstein's rejection of the First Piano Concerto. The work was subsequently premiered by Hans von Bülow, whose pianism had impressed the composer during an appearance in Moscow. Eventually, Rubinstein reconsidered and took up the work.[77] Bülow championed many other Tchaikovsky works both as pianist and conductor.[78]
A middle-aged, balding man with a mustache and small beard, wearing a dark suit and holding a cigarette.
Hans von Bülow

Several factors helped bolster Tchaikovsky's music. One was having several first-rate artists willing to perform it, eventually including Adele Aus der Ohe, Max Erdmannsdörfer, Eduard Nápravník and Sergei Taneyev. Another was a new attitude becoming prevalent among Russian audiences. Previously, they had been satisfied with flashy virtuoso performances of technically demanding but musically lightweight compositions. They gradually began listening with increasing appreciation of the music itself. Tchaikovsky's works were performed frequently, with few delays between their composition and first performances; the publication from 1867 onwards of his songs and great piano music for the home market also helped boost the composer's popularity.[79]

Tchaikovsky began to compose operas. His first, The Voyevoda, based on a play by Alexander Ostrovsky, was premiered in 1869. The composer became dissatisfied with it and, having re-used parts of it in later works, destroyed the manuscript. Undina followed in 1870. Only excerpts were performed and it, too, was destroyed.[80] Between these projects, he started to compose an opera called Mandragora, to a libretto by Sergei Rachinskii; the only music he completed was a short chorus of Flowers and Insects.[81]

The first Tchaikovsky opera to survive intact, The Oprichnik, premiered in 1874. During its composition, he fell out with Ostrovsky. The author of the play The Oprichnik, Ivan Lazhechnikov, had died in 1869, and Tchaikovsky decided to write the libretto himself, modelling his dramatic technique on that of Eugène Scribe. Cui wrote a "characteristically savage press attack" on the opera. Mussorgsky, writing to Vladimir Stasov, disapproved of the opera as pandering to the public. Nevertheless, The Oprichnik continues to be performed from time to time in Russia.[80]

The last of the early operas, Vakula the Smith (Opus 14), was composed in the second half of 1874. The libretto, based on Gogol's Christmas Eve, was to have been set to music by Alexander Serov. With Serov's death, the libretto was opened to a competition with a guarantee that the winning entry would be premiered by the Imperial Mariinsky Theatre. Tchaikovsky was declared the winner, but at the 1876 premiere the opera enjoyed only a lukewarm reception.[82] After Tchaikovsky's death, Rimsky-Korsakov wrote an opera based on the same story, Christmas Eve.[83]

Other works of this period include the Variations on a Rococo Theme for cello and orchestra, the Second and Fourth Symphonies, the ballet Swan Lake and the opera Eugene Onegin.
Emotional life

Discussion of Tchaikovsky's personal life, especially his sexuality, has perhaps been the most extensive of any composer in the 19th century and certainly of any Russian composer of his time.[84] It has also at times caused considerable confusion, from Soviet efforts to expunge all references to same-sex attraction and portray him as a heterosexual to efforts at armchair analysis by Western biographers. A current tendency is to discuss Tchaikovsky's personal life candidly.[85]

Tchaikovsky lived as a bachelor most of his life. In 1877, at the age of 37, he wed a former student, Antonina Miliukova.[86] The marriage was a disaster. Mismatched psychologically and sexually,[87] the couple lived together for only two and a half months before Tchaikovsky left, overwrought emotionally and suffering from an acute writer's block.[88] Tchaikovsky's family remained supportive of him during this crisis and throughout his life.[89] He was also aided by Nadezhda von Meck, the widow of a railway magnate who had begun contact with him not long before the marriage. As well as an important friend and emotional support,[90] she also became his patroness for the next 13 years, which allowed him to focus exclusively on composition.[91]
Sexuality
See also: LGBT history in Russia

Tchaikovsky had clear same-sex tendencies; some of the composer's closest relationships were with men.[92] He sought out the company of other same-sex attracted men in his circle for extended periods, "associating openly and establishing professional connections with them."[76] Relevant portions of his brother Modest's autobiography, where he tells of the composer's sexual orientation, have been published, as have letters previously suppressed by Soviet censors in which Tchaikovsky openly writes of it.[93]
Modest Ilyich Tchaikovsky

More debatable is how comfortable the composer felt with his sexual nature. There are currently two schools of thought. Traditional musicologists such as David Brown have maintained that Tchaikovsky "felt tainted within himself, defiled by something from which he finally realized he could never escape."[94] Another group, which includes Alexander Poznansky and Roland John Wiley, have more recently suggested that the composer experienced "no unbearable guilt" over his sexual nature[76] and "eventually came to see his sexual peculiarities as an insurmountable and even natural part of his personality ... without experiencing any serious psychological damage."[95]
Tchaikovsky and his lover Bob Davydov

Both groups agree that Tchaikovsky remained aware of the negative consequences should knowledge of his orientation become public, especially of the ramifications for his family. While his father continued to hope Tchaikovsky would marry (and may have been unaware of his son's orientation), other members of his loving and supportive family remained more open-minded. Modest shared his sexual orientation and became his literary collaborator, biographer and closest confidant. Tchaikovsky was eventually surrounded by an adoring group of male relatives and friends, which may have aided him in achieving some sort of psychological balance and inner acceptance of his sexual nature.[96]

The level of official tolerance Tchaikovsky may have experienced, which could fluctuate depending on the broad-mindedness of the ruling Tsar, is also open to question. One argument is that general intolerance of same-sex orientation was the rule in 19th century Russia, punishable by imprisonment, loss of all rights, banishment to the provinces or exile from Russia altogether; therefore, Tchaikovsky's fear of social rejection was grounded in some justification.[97] Musicologist Solomon Volkov mentions state documents that indicate men attracted to the same sex "were under tight police surveillance" and maintains that public life in Russia was "based not on laws but on 'understandings.' That means that formally existing laws are applied or ignored based on the position and wishes of the authorities.... No one could feel confident of the future in those conditions (which is one of the goals of a society built on 'understandings')."[98] The other argument is that the Imperial bureaucracy was considerably less draconian in Tchaikovsky's lifetime than previously imagined. Russian society, with its surface veneer of Victorian propriety, may have been no less tolerant than the government.[99]

In any case, Tchaikovsky chose not to neglect social convention and stayed conservative by nature.[100] His love life remained complicated. A combination of upbringing, timidity and deep commitment to relatives precluded his living openly with a male lover.[101] A similar blend of personal inclination and period decorum kept him from having sexual relations with those in his social circle.[102] He regularly sought out anonymous encounters, many of which he reported to Modest; at times, these brought feelings of remorse.[103] He also attempted to be discreet and adjust his tastes to the conventions of Russian society.[104] Nevertheless, many of his colleagues, especially those closest to him, may have either known or guessed his true sexual nature.[105] Tchaikovsky's decision to enter into a heterosexual union and try to lead a double life was prompted by several factors—the possibility of exposure, the willingness to please his father, his own desire for a permanent home and his love of children and family. There is no reason however to suppose that these personal travails impacted negatively on the quality of his musical inspiration or capacity.[76]
Unsuccessful marriage
See also: Désirée Artôt and Antonina Miliukova
Désirée Artôt

In 1868, Tchaikovsky met Belgian soprano Désirée Artôt, then touring Russia with an Italian opera company and causing a sensation with her performances in Moscow.[106] Artôt, according to Tchaikovsky biographers Anthony Holden, was "one of the most lustrous opera stars of her day," with a "beguiling voice."[107] The composer's friend, music critic Hermann Laroche, called her "dramatic singing personified, an opera goddess fusing numerous gifts which would normally be shared among several different artists."[108] Tchaikovsky and Artôt became infatuated and engaged to be married.[109] Even so, Artôt told Tchaikovsky that she would not give up the stage or settle in Russia.[110] Nikolai Rubinstein, fearful that living in a famous singer's shadow would stifle Tchaikovsky's creativity, warned against the union.[111] Undeterred, and while still privately preferring a homosexual lifestyle, the composer discussed wedding plans at length with his father.[100] However, on September 15, 1869, without any communication with Tchaikovsky, Artôt married a Spanish baritone in her company, Mariano Padilla y Ramos.[a 6] Although it is generally thought that Tchaikovsky swiftly got over the affair, it has been suggested that he coded Désirée's name into the Piano Concerto No. 1 in B-flat minor and the tone-poem Fatum.[112] They met on a handful of later occasions and, in October 1888, he wrote Six French Songs, Op. 65, for her, in response to her request for a single song. Tchaikovsky later claimed she was the only woman he ever loved,[113] although Holden and other biographers have surmised that it may have been "the glamorous yet talented diva, rather than the real woman behind the top billing, with whom he had fallen in love."[114]

By the end of 1876, Tchaikovsky had fallen in love with Iosif Kotek, a former student from the Moscow Conservatory. Though he wrote to Modest that Kotek reciprocated his feelings, the composer distanced himself a few months later when Kotek proved to be unfaithful.[115] At roughly the same time another friend, Vladimir Shilovsky, suddenly married. Tchaikovsky did not take the news well. He and Shilovsky, who may have also been homosexual, had shared a mutual bond of affection for just over a decade.[116] Tchaikovsky had previously mentioned the possibility of marriage to Modest, out of concern that public knowledge of his sexuality might scandalize his family.[117] Modest and their sister Sasha, in turn, had warned against such a step.[118] However, Shilovsky's wedding may have spurred him to action.[119] In doing so, he did not consider several factors. One was that his feelings on the matter may have been conflicted. While he wrote to his brother Anatoly about using marriage as a means of securing sexual freedom through leading a "double life," in the same letter he disparaged his homosexual acquaintances who had actually done so.[120] Another factor was that, at 37, Tchaikovsky might have been more set in his bachelor's ways than he would have admitted. Age alone would make that lifestyle much harder to discard or ignore than if he had married much earlier.[121]
A middle aged man with dark hair and a beard, wearing a dark suit and holding a book, sits next to a young woman in a black dress wearing her hair up on her head
Tchaikovsky and Antonina on their honeymoon, 1877
Tchaikovsky on his marriage

There's no doubt that for some months on end I was a bit insane and only now, when I'm completely recovered, have I learned to relate objectively to everything which I did during my brief insanity. That man who in May took it into his head to marry Antonina Ivanova, who during June wrote a whole opera as though nothing had happened, who in July married, who in September fled from his wife, who in November railed at Rome and so on—that man wasn't I, but another Pyotr Ilyich.
—Letter to Tchaikovsky's brother Anatoly, written in Florence, February 18, 1878.[122]

In July 1877, Tchaikovsky married another former student, Antonina Miliukova, after receiving a series of impassioned letters from her.[86] To ensure there would be no interference, he told only Anatoly and his father of his engagement. He did not inform Modest or Sasha until the day before his wedding or Vladimir Shilovsky until the day of the wedding. He invited only Anatoly to the ceremony.[123] Almost as soon as the wedding ended, Tchaikovsky felt he had made a mistake and soon afterwards found that he and Antonina were incompatible psychologically and sexually.[87] If Tchaikovsky attempted to explain his sexual mores to his wife, she did not understand.[124][a 7]

As time passed, Tchaikovsky may have realized that marriage itself, not simply Antonina, may have been wrong for him.[125] He wrote to Sasha that he had "become too used to bachelor life and I cannot recall my loss of freedom without regret."[126] He concluded that, instead of strengthening his personal and social standing, his marriage had actually imperiled it because of the grief and scandal that could result from its failure. Money matters and an inability to compose compounded the situation and drove Tchaikovsky to deeper levels of despair.[127] The couple lived together for only two and a half months before the mounting emotional crisis forced him to leave.[88] He traveled to Clarens, Switzerland for rest and recovery.[128] He and Antonina remained legally married but never lived together again nor had any children,[a 8] though Antonina later gave birth to three children by another man.[129]

Tchaikovsky's marital debacle may have forced him to face the full truth about his sexuality. He never blamed Antonina for the failure of their marriage[130] and he apparently never again considered matrimony or considered himself capable of loving women in the same manner as other men. He admitted to his brother Anatoly that there was "nothing more futile than wanting to be anything other than what I am by nature."[131] Also, though Tchaikovsky would confess it only in periods of deep depression, the episode left him with a deep sense of shame and guilt and an apprehension that Antonina might fully realize and publicize his sexual orientation. Those factors made each of her occasional letters "a great misfortune" which would leave him shaken for days. They also made any news of her, regardless of how minor or innocent, to cause Tchaikovsky lost sleep and appetite, an inability to work and to fixate on imminent death.[132]
Nadezhda von Meck
See also: Nadezhda von Meck
A middle-aged woman wearing her hair up on her head, wearing a dark dress with a large white collar.
Nadezhda von Meck, Tchaikovsky's patroness and confidante from 1877 to 1890

Nadezhda von Meck, the wealthy widow of a railway tycoon, was one of the growing nouveau riche patronizing the arts in the wake of Russia's industrialization. She was eventually joined by timber merchant Mitrofan Belyayev, railway magnate Savva Mamontov and textile manufacturer Pavel Tretyakov. Von Meck differed from her fellow philanthropists in two ways. First, instead of promoting nationalist artists, she helped Tchaikovsky, who was seen as a composer of the Western-oriented aristocracy. Second, while Belyayev, Mamontov and Tretyakov made a public display of their largess, von Meck conducted her support of Tchaikovsky as a largely private matter.[133]

Nadezhda von Meck's support began through Iosif Kotek, who had been hired as a musician in the von Meck household. In 1877, Kotek suggested commissioning some pieces for violin and piano from Tchaikovsky. Von Meck, who had liked what she had heard of his music, agreed. Her subsequent request to the composer became an ongoing correspondence, even as events with Antonina unfolded and made Tchaikovsky's life increasingly difficult.[134] Von Meck and Tchaikovsky exchanged well over 1,000 letters, making theirs perhaps the most closely documented relationship between patron and artist. In these letters Tchaikovsky was more open about his creative processes than he was to any other person.[135]

Von Meck eventually paid Tchaikovsky an annual subsidy of 6,000 rubles, which enabled him to concentrate on composition.[91] With this patronage came a relationship that, while remaining epistolary, grew extremely intimate.[90] She suddenly ceased her financial subsidy in 1890 as a result of her own financial difficulties. While there is no evidence she intended to also discontinue her friendship and communication, this was nevertheless brought about through the machinations of her son-in-law, Tchaikovsky's erstwhile student Władysław Pachulski, who had an exalted opinion of his own compositional abilities and was resentful that Tchaikovsky did not share it. While Tchaikovsky was not in as urgent a need of her money as he had been, her friendship and encouragement had remained an integral part of his emotional life. He remained bewildered and resentful about her absence for the remaining three years of his life, and she was just as distressed about his apparent dropping of her friendship, which she was led to believe was because he had never cared for her personally and he had no further use for her once her subsidy had stopped. This was completely untrue.[136]
Years of wandering

Tchaikovsky remained abroad for a year after the disintegration of his marriage, during which he completed Eugene Onegin, orchestrated the Fourth Symphony and composed the Violin Concerto.[137] He returned to the Moscow Conservatory in the autumn of 1879 but only as a temporary move; he informed Nikolai Rubinstein on the day of his arrival that he would stay no longer than December.[138][a 9] Once his professorship had ended officially, he traveled incessantly throughout Europe and rural Russia. Assured of a regular income from von Meck, he lived mainly alone, did not stay long anywhere and avoided social contact whenever possible.[139] His troubles with Antonina continued. She agreed to divorce him, then refused. While he was on an extended visit to Moscow, she moved into an apartment directly above where he was staying.[140] Tchaikovsky listed her accusations in detail to Modest: "I am a deceiver who married her in order to hide my true nature ... I insulted her every day, her sufferings at my hands were great ... she is appalled by my shameful vice, etc., etc." He may have lived the rest of his life in dread of Antonina's power to expose him publicly.[141] This could be why his best work from this period, except for the piano trio which he wrote upon the death of Nikolai Rubinstein, is found in genres which did not require deep personal expression.[140]
A stocky, balding man with a beard, wearing a dark military uniform.
Tsar Alexander III

Tchaikovsky's foreign reputation grew rapidly. In Russia, though, it was "considered obligatory [in progressive musical circles in Russia] to treat Tchaikovsky as a renegade, a master overly dependent on the West."[142] In 1880 this assessment changed. During commemoration ceremonies for the Pushkin Monument in Moscow, novelist Fyodor Dostoyevsky charged that poet and playwright Alexander Pushkin had given a prophetic call to Russia for "universal unity" with the West.[142] An unprecedented acclaim for Dostoyevsky's message spread throughout Russia, and with it disdain for Tchaikovsky's music evaporated. He even drew a cult following among the young intelligentsia of Saint Petersburg, including Alexandre Benois, Léon Bakst and Sergei Diaghilev.[143]

In 1880, the Cathedral of Christ the Saviour neared completion in Moscow; the 25th anniversary of the coronation of Alexander II in 1881 was imminent;[a 10] and the 1882 Moscow Arts and Industry Exhibition was in the planning stage. Nikolai Rubinstein suggested a grand commemorative piece for association with these related festivities. Tchaikovsky began the project in October 1880, finishing it within six weeks. He wrote to Nadezhda von Meck that the resulting work, the 1812 Overture, would be "very loud and noisy, but I wrote it with no warm feeling of love, and therefore there will probably be no artistic merits in it."[144] He also warned conductor Eduard Nápravník that "I shan't be at all surprised and offended if you find that it is in a style unsuitable for symphony concerts."[144] Nevertheless, this work has become for many "the piece by Tchaikovsky they know best."[145]

On 23 March 1881, Nikolai Rubinstein died in Paris. Tchaikovsky, holidaying in Rome, went immediately to attend the funeral. He arrived in Paris too late for the ceremony but was in the cortege which accompanied Rubinstein's coffin by train to Russia.[146] In December, he started work on his Piano Trio in A minor, "dedicated to the memory of a great artist."[147] The trio was first performed privately at the Moscow Conservatory on the first anniversary of Rubinstein's death.[148][a 11] The piece became extremely popular during the composer's lifetime and became Tchaikovsky's own elegy when played at memorial concerts in Moscow and St. Petersburg in November 1893.[149]
Return to Russia

Now 44 years old, in 1884 Tchaikovsky began to shed his unsociability and restlessness. In March of that year, Tsar Alexander III conferred upon him the Order of St. Vladimir (fourth class), which carried with it hereditary nobility[150] and won Tchaikovsky a personal audience with the Tsar.[151] This was a visible seal of official approval which advanced Tchaikovsky's social standing.[150] This advance may have been cemented in the composer's mind by the great success of his Orchestral Suite No. 3 at its January 1885 premiere in Saint Petersburg, under von Bülow's direction,[152] at which the press was unanimously favorable. Tchaikovsky wrote to von Meck: "I have never seen such a triumph. I saw the whole audience was moved, and grateful to me. These moments are the finest adornments of an artist's life. Thanks to these it is worth living and laboring.".[152]
A blue two-story house with white trim and many windows, surrounded by birch trees.
Tchaikovsky's last home, in Klin, now the Tchaikovsky Museum

In 1885 the tsar requested a new production of Eugene Onegin to be staged at the Bolshoi Kamenny Theatre in Saint Petersburg. (Its only other production had been by students from the Conservatory.) By having the opera staged there and not at the Mariinsky Theatre, he served notice that Tchaikovsky's music was replacing Italian opera as the official imperial art. In addition, thanks to Ivan Vsevolozhsky, Director of the Imperial Theaters and a patron of the composer, Tchaikovsky was awarded a lifetime annual pension of 3,000 rubles from the Tsar. This made him the premier court composer, in practice if not in actual title.[153]

Despite his disdain for public life, Tchaikovsky now participated in it both as a consequence of his increasing celebrity and because he felt it his duty to promote Russian music. He helped support his former pupil Sergei Taneyev, who was now director of Moscow Conservatory, by attending student examinations and negotiating the sometimes sensitive relations among various members of the staff. Tchaikovsky also served as director of the Moscow branch of the Russian Musical Society during the 1889-1890 season. In this post, he invited many international celebrities to conduct, including Johannes Brahms, Antonín Dvořák and Jules Massenet, although not all of them accepted.[151]

Tchaikovsky also promoted Russian music as a conductor,[151] as which he had sought to establish himself for at least a decade, believing that it would reinforce his success.[154] In January 1887 he substituted at the Bolshoi Theater in Moscow at short notice for performances of his opera Cherevichki.[155] Within a year of the Cherevichki performances, Tchaikovsky was in considerable demand throughout Europe and Russia, which helped him overcome life-long stage fright and boosted his self-assurance.[156] Conducting brought him to America in 1891, where he led the New York Music Society's orchestra in his Festival Coronation March at the inaugural concert of the Carnegie Hall.[157]

In 1888 Tchaikovsky led the premiere of his Fifth Symphony in Saint Petersburg, repeating the work a week later with the first performance of his tone poem Hamlet. Although critics proved hostile, with César Cui calling the symphony "routine" and "meretricious", both works were received with extreme enthusiasm by audiences and Tchaikovsky, undeterred, continued to conduct the symphony in Russia and Europe.[158]
Belyayev circle and growing reputation
See also: Pyotr Ilyich Tchaikovsky and the Belyayev circle

In November 1887, Tchaikovsky arrived in Saint Petersburg in time to hear several of the Russian Symphony Concerts, devoted exclusively to the music of Russian composers. One included the first complete performance of his revised First Symphony; another featured the final version of Third Symphony of Nikolai Rimsky-Korsakov, with whose circle Tchaikovsky was already in touch.[159] Rimsky-Korsakov, with Alexander Glazunov, Anatoly Lyadov and several other nationalistically minded composers and musicians, had formed a group known the Belyayev circle, named after a merchant and amateur musician who became an influential music patron and publisher.[160] Tchaikovsky's spent much time in this circle, becoming far more at ease with them than he had been with the 'Five' and increasingly confident in showcasing his music alongside theirs.[161] This relationship lasted until Tchaikovsky's death.[162][163]

In 1892, Tchaikovsky was voted a member of the Académie des Beaux-Arts in France, only the second Russian subject to be honored so (the first was sculptor Mark Antokolski).[164] The following year, the University of Cambridge in England awarded Tchaikovsky an honorary Doctor of Music degree.[165]
Death
See also: Death of Pyotr Ilyich Tchaikovsky and Symphony No. 6 (Tchaikovsky)

On 30 October 1893 Tchaikovsky conducted the premiere of his Sixth Symphony, the Pathétique In Saint Petersburg. Nine days later, Tchaikovsky died there, aged 53. He was interred in Tikhvin Cemetery at the Alexander Nevsky Monastery, near the graves of fellow-composers Alexander Borodin, Mikhail Glinka, and Modest Mussorgsky; later, Rimsky-Korsakov and Balakirev were also buried nearby.[166]

While Tchaikovsky's death has traditionally been attributed to cholera, most probably contracted through drinking contaminated water several days earlier,[167] some have theorized that his death was a suicide.[168] Opinion has been summarized as follows: "The polemics over [Tchaikovsky's] death have reached an impasse ... Rumor attached to the famous die hard ... As for illness, problems of evidence offer little hope of satisfactory resolution: the state of diagnosis; the confusion of witnesses; disregard of long-term effects of smoking and alcohol. We do not know how Tchaikovsky died. We may never find out.
""",

# Dobri Petrov Chintulov
"""
Dobri Petrov Chintulov was a Bulgarian poet, teacher and composer of the Bulgarian National Revival period.

He was born in the town of Sliven in September 1822 to the family of a craftsman, Chintulov studied at the Greek school in his hometown. Due to a lack of funds, however, he was forced to drop out and move to Tarnovo, where he worked and visited the local class school in 1838 for around six months. From there he set off to Bucharest, Wallachia, where he studied for a year and a half. Receiving a scholarship from the Russian government, Chintulov moved to Odessa in the Russian Empire in 1840, assisted by his fellow townsman Dimitar Diamandiev, living in Brăila. After a stay of several months in Brăila, Chintulov returned to Sliven in 1850 and worked as a teacher for seven years; he established a cultural centre (chitalishte), joined the Bulgarian Church struggle and endorsed the idea of Bulgarian independence. In that period, he wrote a number of patriotic and revolutionary songs and poems, some of which became very popular and renowned as anthems of the revolution.

Provoking the animosity of the Turkophile and Grecoman circles in Sliven who even attempted to assassinate him, Chintulov moved to Yambol in 1858 and worked there as a head teacher until 1861. From 1861 to 1871, he was back to Sliven as a head teacher. In 1871, he moved to Istanbul (Tsarigrad) as Sliven's representative for the creation of the Bulgarian Exarchate's statute. Upon returning to Sliven, he worked as a teacher once again for three years, but had to quit due to problems with his sight.

Although ill and half-blind, Chintulov was among those who welcomed the liberating Russian forces in Sliven during the Russo-Turkish War of 1877–1878 on 17 November and held a speech. Receiving a pension until the end of his life, Chintulov died in Sliven on 27 March 1886, disappointed with the post-Liberation reality.

Chintulov's poetic legacy is not large in numbers, as only around 20 of his poems have survived: he had to burn his manuscripts twice. Only three of his songs have been published, but his works had a tremendous influence on the Bulgarian youth of the time and are still well known as classic Bulgarian revolutionary music.
""",

# Kathleen McNulty
"""
Kathleen McNulty was born in Ireland in 1902 but emigrated to the United States as a young child. We should explain the names under which we have listed her in this archive. She married John Mauchly in 1948 becoming Kay Mauchly then, some years after John Mauchly's death in 1980, she married Severo Antonelli. Her education was in Catholic Schools in the United States before entering Chestnut Hill College for Women in Philadelphia. At Chestnut Hill College she studied mathematics and it was in that subject that she graduated in 1942.

Of course 1942 was in the middle of World War II and by this time the war was strongly affecting the direction of academic research. The United States was specifically directing its research schools and staff towards the war effort. The University of Pennsylvania's Moore School of Engineering began putting on training courses for electronics and other disciplines as part of this war effort. They also began early research in the use of computers.

The Ballistic Research Laboratory had been set up at Aberdeen, in Harford county, northeastern Maryland as part of the Aberdeen Proving Ground, a military weapons testing site which had been established in 1917 during World War I. The Ballistic Research Laboratory consisted of staff from the Moore School and staff from the Aberdeen Proving Ground using their expertise on joint projects.

After graduating Kay Mc'Nulty was employed as a mathematician by the Moore School of Engineering where she worked on preparing firing tables for guns. McNulty described the work which she did in the following way:-

    We did have desk calculators at that time, mechanical and driven with electric motors, that could do simple arithmetic. You'd do a multiplication and when the answer appeared, you had to write it down to reenter it into the machine to do the next calculation. We were preparing a firing table for each gun, with maybe 1,800 simple trajectories. To hand-compute just one of these trajectories took 30 or 40 hours of sitting at a desk with paper and a calculator. As you can imagine, they were soon running out of young women to do the calculations. Actually, my title working for the ballistics project was "computer". The idea was that I not only did arithmetic but also made the decision on what to do next. ENIAC made me, one of the first "computers", obsolete.

The ENIAC computer (Electronic Numerical Integrator and Computer) which McNulty refers to in the above quote was being constructed by John Mauchly and John Eckert in the Moore School of Engineering during the war years. It was designed for the specific task of compiling tables for the trajectories of bombs and shells to take over the calculations which McNulty and about 75 other women were carrying out. However the war had ended before the machine came into service but it was still used for the numerical solution of differential equations as intended. McNulty was one of six women who became operators of ENIAC making very substantial contributions to computer science, although it took many years before they received the credit which they deserve for their pioneering work.

Petzinger, in, describes the way that McNulty used ENIAC to solve differential equations after the construction of the machine was complete in February 1946:-

    The first task was breaking down complex differential equations into the smallest possible steps. Each of these had to be routed to the proper bank of electronics and performed in sequence - not simply a linear progression but a parallel one, for the ENIAC, amazingly, could conduct many operations simultaneously. Every datum and instruction had to reach the correct location in time for the opeation that depended on it, to within 1/5000th of a second.

In 1948 McNulty married John Mauchly, one of the two designers of the ENIAC computer. By this time John Mauchly had left the Moore School and was designing further computers in partenership with John Eckert. John and Kay Mauchly lived on a farm in Amber Pennsylvannia and Kay continued to work with with her husband on the design of computer programs for the later BINAC and UNIVAC computers. She contributed skills in software design to these projects which complemented her husbands expertise in hardware design.

Some years after the death of her husband in 1980, Kay married Severo Antonelli and lived in Pennsylvania.
Kay Antonelli was a keynote speaker at the Women In Technology International's East Coast Summit in Boston in 1998.

Antonelli died of cancer at Keystone Hospice in Wyndmoor.
""",

# James Wiegold
"""
James Wiegold was known to all his friends and colleagues as Jim. We give details of the first years of his life up to the time he went to Manchester University by quoting, almost verbatim, from [3]. James Wiegold was born near Caerphilly on 15 April 1934. This fact was somewhat obscure to him through his childhood: for many years he celebrated his birthday erroneously on 17 April. James, or Jimmy Boy as he was then called, much to his later chagrin, was the fifth child of Walter Wiegold, a mining surface worker originally from London, and his Welsh wife Elizabeth, a woman of remarkable intelligence and forceful personality. The family was caught at the harsh end of the 1930s depression, with Walter unemployed until rearmament for war. Their house in Abertridwr, where Jim spent most of his childhood, had no electricity except for a single electric light bulb introduced during his childhood. The children were sometimes short of food and regularly short of clothing: at one point Jim was unable to go to school because his mother could find no shoes for him, while on another occasion the only coat she could find was a girl's coat. He simply dumped the offending item somewhere, rather than go to school in it. At the right times of year, however, food was more easily supplemented from natural sources. The family regularly foraged for food, including blackberries, bilberries, sloes, burdock, nettles, trout, and rabbits.

One might expect that this story of financial deprivation would be balanced from the beginning by extraordinary academic success. In fact, in the early years of primary school the future mathematics professor was thought to be backward. Despite this inauspicious start, however, at the age of 10 Jim won a scholarship to Caerphilly Boys Grammar School, a success almost unheard of in his community. On his first day in September 1944, the whole street waved him off on the train from Abertridwr to Caerphilly. At the grammar school, the educationally deprived child's world opened up: many times he has recalled the day he brought home his Latin books and peeped awestruck into this brave new world. A few years later, however, a potential disaster struck. The teenage Jim was looking out of the window at home one evening and was surprised to see, as he thought, that "they had put a second light on Aber mountain." When he looked back into the room, he saw that there was suddenly a second everything. This was the beginning of the double vision with which he lived throughout his life. He always saw two images of everything, with one image moving round the other. At first, the teenager did not dare to tell anyone, because he thought he would not be believed, but when he started falling down stairs and pouring tea into the wrong cup his mother realised that there must be a problem. The diagnosis was a minor brain haemorrhage; the prognosis extremely discouraging, with the medical profession proclaiming that he would never be able to go to university or to pursue any worthwhile activity. Naturally, Jim was not going to let that stand in his way. The only everyday activity which was closed to him was driving. Go to university he certainly did, to study mathematics at Manchester.

When Jim went north in 1951, he had never previously been out of the counties of Glamorganshire, Gloucestershire, Herefordshire and Somerset and had never seen a bathroom. At first he was horrendously homesick, but soon he warmed to the intellectual, social, and cultural opportunities offered by a university city. Jim used to go to Halle concerts in the Free Trade Hall. One occasion was the first time Jim had ever heard, either live or recorded, Beethoven's fifth Symphony: he recounted his overwhelming excitement and a feeling of "walking on air". At Manchester, Jim met a fellow mathematics undergraduate Christine. Their first meeting was at a mathematics department Christmas dance, and she was singularly unimpressed with him, but soon a friendship grew which flourished into a romance and finally a marriage, on Easter Monday, 7 April 1958. Not only were Jim and Christine fellow undergraduates but both also became research students of Bernhard Neumann. Jim and Christine Wiegold had three children, Helen, Alison and Richard.

Wiegold had graduated B.Sc. with First Class Honours in Mathematics from Manchester in 1954, then spent a year working for his M.Sc. which he received one year later. He submitted his doctoral dissertation entitled Nilpotent products of groups with amalgamations in 1958 and was awarded his Ph.D. In his thesis he combined two ideas, namely the theory of generalized free and direct products of groups with amalgamations, and the theory of nilpotent products and verbal products of groups. By the time he received his doctorate he was already employed as an Assistant Lecturer at the University College of North Staffordshire, now the University of Keele. He held this position from 1957 to 1960 when he moved back to Manchester as a Lecturer in the Faculty of Technology. The Pure Mathematics Department in the Faculty of Technology was led by Hanna Neumann and Wiegold had already started joint work with her on certain products of groups which they called linked products before he joined the staff at Manchester. Their joint paper Linked products and linked embeddings of groups appeared in 1960. In 1963 Wiegold left Manchester and returned to Wales when he was appointed as a Lecturer at the University College of South Wales and Monmouthshire, now Cardiff University. He returned with his young family to Wales, in order to be closer to his now-widowed father and siblings, rather than because of any pro-Welsh drive.

In 1966 Wiegold was promoted to Senior Lecturer. Then in 1968 he went to the School of General Studies of the Australian National University where he spent two years, first as a Visiting Senior Lecturer and in the second year as a Visiting Reader. Both Bernhard and Hanna Neumann had left Manchester in the same year that Wiegold went to Cardiff. When Wiegold visited, Hanna Neumann held the chair of pure mathematics in the School of General Studies and Bernhard Neumann was Head of the Mathematics Department at the Institute of Advanced Studies. Wiegold's youngest sister Liz went out to Australia with Jim and his family, and remained at ANU as a history student after they left. Liz married Daniel Neumann, the youngest of Bernhard and Hanna Neumann's children. Wiegold was promoted to a Readership at Cardiff in 1969.
""",


]